// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/dilex.proto

package dilex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DilexSync_Sync_FullMethodName   = "/dilex.v1.DilexSync/Sync"
	DilexSync_Status_FullMethodName = "/dilex.v1.DilexSync/Status"
)

// DilexSyncClient is the client API for DilexSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DilexSync is the transport service between two DILEX nodes. It exposes a
// single bidirectional sync stream and a unary status method. All priority
// ordering and durability guarantees are enforced by the sender - the service
// is the wire contract only.
type DilexSyncClient interface {
	// Sync is the primary bidirectional stream between two DILEX nodes.
	//
	// Protocol:
	//  1. Sender sends SenderMsg{handshake: SyncRequest}.
	//  2. Receiver responds with ReceiverMsg{ready: SyncReady}.
	//  3. Sender streams SenderMsg{payload: Payload} in priority order.
	//  4. Receiver streams ReceiverMsg{ack: Ack} as each payload is processed.
	//     Acks may be pipelined - the receiver does not need to wait for the
	//     sender to pause. The sender's WAL removal waits for each individual Ack.
	//  5. On disconnect, sender reopens the stream and resumes from last_acked_id.
	//
	// A single stream minimises round trips on severely constrained connections.
	Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SenderMsg, ReceiverMsg], error)
	// Status returns the current state of the local DILEX instance.
	// Corresponds to the Status() method on the public client interface.
	// Also serves as a connectivity probe before opening a Sync stream.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type dilexSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewDilexSyncClient(cc grpc.ClientConnInterface) DilexSyncClient {
	return &dilexSyncClient{cc}
}

func (c *dilexSyncClient) Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SenderMsg, ReceiverMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DilexSync_ServiceDesc.Streams[0], DilexSync_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SenderMsg, ReceiverMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DilexSync_SyncClient = grpc.BidiStreamingClient[SenderMsg, ReceiverMsg]

func (c *dilexSyncClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DilexSync_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DilexSyncServer is the server API for DilexSync service.
// All implementations must embed UnimplementedDilexSyncServer
// for forward compatibility.
//
// DilexSync is the transport service between two DILEX nodes. It exposes a
// single bidirectional sync stream and a unary status method. All priority
// ordering and durability guarantees are enforced by the sender - the service
// is the wire contract only.
type DilexSyncServer interface {
	// Sync is the primary bidirectional stream between two DILEX nodes.
	//
	// Protocol:
	//  1. Sender sends SenderMsg{handshake: SyncRequest}.
	//  2. Receiver responds with ReceiverMsg{ready: SyncReady}.
	//  3. Sender streams SenderMsg{payload: Payload} in priority order.
	//  4. Receiver streams ReceiverMsg{ack: Ack} as each payload is processed.
	//     Acks may be pipelined - the receiver does not need to wait for the
	//     sender to pause. The sender's WAL removal waits for each individual Ack.
	//  5. On disconnect, sender reopens the stream and resumes from last_acked_id.
	//
	// A single stream minimises round trips on severely constrained connections.
	Sync(grpc.BidiStreamingServer[SenderMsg, ReceiverMsg]) error
	// Status returns the current state of the local DILEX instance.
	// Corresponds to the Status() method on the public client interface.
	// Also serves as a connectivity probe before opening a Sync stream.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedDilexSyncServer()
}

// UnimplementedDilexSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDilexSyncServer struct{}

func (UnimplementedDilexSyncServer) Sync(grpc.BidiStreamingServer[SenderMsg, ReceiverMsg]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedDilexSyncServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDilexSyncServer) mustEmbedUnimplementedDilexSyncServer() {}
func (UnimplementedDilexSyncServer) testEmbeddedByValue()                   {}

// UnsafeDilexSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DilexSyncServer will
// result in compilation errors.
type UnsafeDilexSyncServer interface {
	mustEmbedUnimplementedDilexSyncServer()
}

func RegisterDilexSyncServer(s grpc.ServiceRegistrar, srv DilexSyncServer) {
	// If the following call panics, it indicates UnimplementedDilexSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DilexSync_ServiceDesc, srv)
}

func _DilexSync_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DilexSyncServer).Sync(&grpc.GenericServerStream[SenderMsg, ReceiverMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DilexSync_SyncServer = grpc.BidiStreamingServer[SenderMsg, ReceiverMsg]

func _DilexSync_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DilexSyncServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DilexSync_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DilexSyncServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DilexSync_ServiceDesc is the grpc.ServiceDesc for DilexSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DilexSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dilex.v1.DilexSync",
	HandlerType: (*DilexSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _DilexSync_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _DilexSync_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/dilex.proto",
}
