// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/dilex.proto

package dilex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload is the unit of transfer. Assigned a unique ID and priority by the
// sender before the WAL write. DILEX does not inspect the contents of data.
type Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID v4 assigned at Send(). Stable across reconnects - the sync manager
	// uses this to resume from the last acknowledged position.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Opaque application data. DILEX does not inspect or transform this.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Priority level. 1 = highest, 5 = lowest. Payloads at the same level
	// are ordered by created_at_ms (FIFO) to prevent starvation.
	Priority uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Sender-side creation time in milliseconds since Unix epoch. Used only
	// for intra-priority FIFO ordering. Clock skew between nodes does not
	// affect correctness - only relative ordering within a priority level.
	CreatedAtMs   int64 `protobuf:"varint,4,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_dilex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dilex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_dilex_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Payload) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Payload) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

// Ack is the receiver's explicit acknowledgment for a single payload.
// The sender removes the payload from the WAL only after receiving an Ack.
type Ack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mirrors the id of the payload being acknowledged.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// true = accepted; sender removes from WAL.
	// false = rejected (e.g. decode error, receiver fault); sender removes from
	// WAL, increments total_rejected, and does not retry. Retry is an
	// application-layer concern.
	Ok            bool `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_dilex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dilex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_dilex_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// SyncRequest is the first message sent by the sender on connect or reconnect.
// Establishes the resume point so the receiver can skip already-acknowledged
// payloads.
type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the last payload the sender received an Ack for.
	// Empty string on first connect - receiver starts from the beginning.
	LastAckedId   string `protobuf:"bytes,1,opt,name=last_acked_id,json=lastAckedId,proto3" json:"last_acked_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_dilex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dilex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_dilex_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetLastAckedId() string {
	if x != nil {
		return x.LastAckedId
	}
	return ""
}

// SyncReady is the receiver's response to a SyncRequest. Signals that the
// receiver is ready and confirms the resume point.
type SyncReady struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID the receiver will resume from. Empty means start from the beginning.
	ResumeFromId  string `protobuf:"bytes,1,opt,name=resume_from_id,json=resumeFromId,proto3" json:"resume_from_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncReady) Reset() {
	*x = SyncReady{}
	mi := &file_proto_dilex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReady) ProtoMessage() {}

func (x *SyncReady) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dilex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReady.ProtoReflect.Descriptor instead.
func (*SyncReady) Descriptor() ([]byte, []int) {
	return file_proto_dilex_proto_rawDescGZIP(), []int{3}
}

func (x *SyncReady) GetResumeFromId() string {
	if x != nil {
		return x.ResumeFromId
	}
	return ""
}

// SenderMsg is the envelope for all messages sent by the initiating node on a
// Sync stream. The first message MUST be a handshake. All subsequent messages
// MUST be payloads.
type SenderMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*SenderMsg_Handshake
	//	*SenderMsg_Payload
	Body          isSenderMsg_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderMsg) Reset() {
	*x = SenderMsg{}
	mi := &file_proto_dilex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderMsg) ProtoMessage() {}

func (x *SenderMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dilex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderMsg.ProtoReflect.Descriptor instead.
func (*SenderMsg) Descriptor() ([]byte, []int) {
	return file_proto_dilex_proto_rawDescGZIP(), []int{4}
}

func (x *SenderMsg) GetBody() isSenderMsg_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SenderMsg) GetHandshake() *SyncRequest {
	if x != nil {
		if x, ok := x.Body.(*SenderMsg_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *SenderMsg) GetPayload() *Payload {
	if x != nil {
		if x, ok := x.Body.(*SenderMsg_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isSenderMsg_Body interface {
	isSenderMsg_Body()
}

type SenderMsg_Handshake struct {
	Handshake *SyncRequest `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type SenderMsg_Payload struct {
	Payload *Payload `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

func (*SenderMsg_Handshake) isSenderMsg_Body() {}

func (*SenderMsg_Payload) isSenderMsg_Body() {}

// ReceiverMsg is the envelope for all messages sent by the receiving node on a
// Sync stream. The first message MUST be a ready. All subsequent messages MUST
// be acks.
type ReceiverMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ReceiverMsg_Ready
	//	*ReceiverMsg_Ack
	Body          isReceiverMsg_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiverMsg) Reset() {
	*x = ReceiverMsg{}
	mi := &file_proto_dilex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiverMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverMsg) ProtoMessage() {}

func (x *ReceiverMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dilex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverMsg.ProtoReflect.Descriptor instead.
func (*ReceiverMsg) Descriptor() ([]byte, []int) {
	return file_proto_dilex_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiverMsg) GetBody() isReceiverMsg_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ReceiverMsg) GetReady() *SyncReady {
	if x != nil {
		if x, ok := x.Body.(*ReceiverMsg_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *ReceiverMsg) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*ReceiverMsg_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isReceiverMsg_Body interface {
	isReceiverMsg_Body()
}

type ReceiverMsg_Ready struct {
	Ready *SyncReady `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type ReceiverMsg_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*ReceiverMsg_Ready) isReceiverMsg_Body() {}

func (*ReceiverMsg_Ack) isReceiverMsg_Body() {}

// StatusRequest is empty. The Status RPC requires a request message by
// convention; there is nothing to send.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_dilex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dilex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_dilex_proto_rawDescGZIP(), []int{6}
}

// StatusResponse reflects the current state of the local DILEX instance.
// All counters are cumulative since process start and are not persisted.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of payloads currently in the queue awaiting transmission.
	QueueDepth uint64 `protobuf:"varint,1,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	// Total payloads acknowledged with ok=true by the remote since process start.
	TotalSent uint64 `protobuf:"varint,2,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	// Total payloads rejected (ok=false) by the remote since process start.
	// A non-zero value indicates an application-layer issue on the receiver.
	// DILEX does not retry rejections.
	TotalRejected uint64 `protobuf:"varint,3,opt,name=total_rejected,json=totalRejected,proto3" json:"total_rejected,omitempty"`
	// Whether the sync manager currently has an active stream to the remote node.
	Connected bool `protobuf:"varint,4,opt,name=connected,proto3" json:"connected,omitempty"`
	// ID of the most recently acknowledged payload. Empty if nothing has been
	// acknowledged in this process lifetime.
	LastAckedId   string `protobuf:"bytes,5,opt,name=last_acked_id,json=lastAckedId,proto3" json:"last_acked_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_dilex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dilex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_dilex_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetQueueDepth() uint64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *StatusResponse) GetTotalSent() uint64 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *StatusResponse) GetTotalRejected() uint64 {
	if x != nil {
		return x.TotalRejected
	}
	return 0
}

func (x *StatusResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *StatusResponse) GetLastAckedId() string {
	if x != nil {
		return x.LastAckedId
	}
	return ""
}

var File_proto_dilex_proto protoreflect.FileDescriptor

const file_proto_dilex_proto_rawDesc = "" +
	"\n" +
	"\x11proto/dilex.proto\x12\bdilex.v1\"m\n" +
	"\aPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\rR\bpriority\x12\"\n" +
	"\rcreated_at_ms\x18\x04 \x01(\x03R\vcreatedAtMs\"%\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"1\n" +
	"\vSyncRequest\x12\"\n" +
	"\rlast_acked_id\x18\x01 \x01(\tR\vlastAckedId\"1\n" +
	"\tSyncReady\x12$\n" +
	"\x0eresume_from_id\x18\x01 \x01(\tR\fresumeFromId\"y\n" +
	"\tSenderMsg\x125\n" +
	"\thandshake\x18\x01 \x01(\v2\x15.dilex.v1.SyncRequestH\x00R\thandshake\x12-\n" +
	"\apayload\x18\x02 \x01(\v2\x11.dilex.v1.PayloadH\x00R\apayloadB\x06\n" +
	"\x04body\"e\n" +
	"\vReceiverMsg\x12+\n" +
	"\x05ready\x18\x01 \x01(\v2\x13.dilex.v1.SyncReadyH\x00R\x05ready\x12!\n" +
	"\x03ack\x18\x02 \x01(\v2\r.dilex.v1.AckH\x00R\x03ackB\x06\n" +
	"\x04body\"\x0f\n" +
	"\rStatusRequest\"\xb9\x01\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vqueue_depth\x18\x01 \x01(\x04R\n" +
	"queueDepth\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x02 \x01(\x04R\ttotalSent\x12%\n" +
	"\x0etotal_rejected\x18\x03 \x01(\x04R\rtotalRejected\x12\x1c\n" +
	"\tconnected\x18\x04 \x01(\bR\tconnected\x12\"\n" +
	"\rlast_acked_id\x18\x05 \x01(\tR\vlastAckedId2\x80\x01\n" +
	"\tDilexSync\x126\n" +
	"\x04Sync\x12\x13.dilex.v1.SenderMsg\x1a\x15.dilex.v1.ReceiverMsg(\x010\x01\x12;\n" +
	"\x06Status\x12\x17.dilex.v1.StatusRequest\x1a\x18.dilex.v1.StatusResponseB/Z-github.com/relumic/dilex/internal/proto/dilexb\x06proto3"

var (
	file_proto_dilex_proto_rawDescOnce sync.Once
	file_proto_dilex_proto_rawDescData []byte
)

func file_proto_dilex_proto_rawDescGZIP() []byte {
	file_proto_dilex_proto_rawDescOnce.Do(func() {
		file_proto_dilex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dilex_proto_rawDesc), len(file_proto_dilex_proto_rawDesc)))
	})
	return file_proto_dilex_proto_rawDescData
}

var file_proto_dilex_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_dilex_proto_goTypes = []any{
	(*Payload)(nil),        // 0: dilex.v1.Payload
	(*Ack)(nil),            // 1: dilex.v1.Ack
	(*SyncRequest)(nil),    // 2: dilex.v1.SyncRequest
	(*SyncReady)(nil),      // 3: dilex.v1.SyncReady
	(*SenderMsg)(nil),      // 4: dilex.v1.SenderMsg
	(*ReceiverMsg)(nil),    // 5: dilex.v1.ReceiverMsg
	(*StatusRequest)(nil),  // 6: dilex.v1.StatusRequest
	(*StatusResponse)(nil), // 7: dilex.v1.StatusResponse
}
var file_proto_dilex_proto_depIdxs = []int32{
	2, // 0: dilex.v1.SenderMsg.handshake:type_name -> dilex.v1.SyncRequest
	0, // 1: dilex.v1.SenderMsg.payload:type_name -> dilex.v1.Payload
	3, // 2: dilex.v1.ReceiverMsg.ready:type_name -> dilex.v1.SyncReady
	1, // 3: dilex.v1.ReceiverMsg.ack:type_name -> dilex.v1.Ack
	4, // 4: dilex.v1.DilexSync.Sync:input_type -> dilex.v1.SenderMsg
	6, // 5: dilex.v1.DilexSync.Status:input_type -> dilex.v1.StatusRequest
	5, // 6: dilex.v1.DilexSync.Sync:output_type -> dilex.v1.ReceiverMsg
	7, // 7: dilex.v1.DilexSync.Status:output_type -> dilex.v1.StatusResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_dilex_proto_init() }
func file_proto_dilex_proto_init() {
	if File_proto_dilex_proto != nil {
		return
	}
	file_proto_dilex_proto_msgTypes[4].OneofWrappers = []any{
		(*SenderMsg_Handshake)(nil),
		(*SenderMsg_Payload)(nil),
	}
	file_proto_dilex_proto_msgTypes[5].OneofWrappers = []any{
		(*ReceiverMsg_Ready)(nil),
		(*ReceiverMsg_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dilex_proto_rawDesc), len(file_proto_dilex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dilex_proto_goTypes,
		DependencyIndexes: file_proto_dilex_proto_depIdxs,
		MessageInfos:      file_proto_dilex_proto_msgTypes,
	}.Build()
	File_proto_dilex_proto = out.File
	file_proto_dilex_proto_goTypes = nil
	file_proto_dilex_proto_depIdxs = nil
}
